**Step-1:Import packages**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**step-2:Read csv**

In [2]:
visa_df=pd.read_csv(r"C:\Users\B VENKATA SAILAJA\Documents\Datasets_GenAi\Visadataset.csv")
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

**separate cata and nume Columns**

In [6]:
cat=visa_df.select_dtypes(include='object').columns.tolist()
cat

['case_id',
 'continent',
 'education_of_employee',
 'has_job_experience',
 'requires_job_training',
 'region_of_employment',
 'unit_of_wage',
 'full_time_position',
 'case_status']

In [7]:
num=visa_df.select_dtypes(exclude='object').columns.tolist()
num

['no_of_employees', 'yr_of_estab', 'prevailing_wage']

- frequency table
- bar chat
- relative frequency table
- pie chart

**Step-3:Frequency table**

In [8]:
cat

['case_id',
 'continent',
 'education_of_employee',
 'has_job_experience',
 'requires_job_training',
 'region_of_employment',
 'unit_of_wage',
 'full_time_position',
 'case_status']

In [10]:
visa_df['continent']

0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
          ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia
Name: continent, Length: 25480, dtype: object

In [13]:
visa_df['continent'].unique()
#to know the repeting values

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [15]:
visa_df['continent'].nunique()#how many times repeted

6

- There are 25480 applicants from 6 countries
- number of applicants from each continent: frequency table

In [20]:
#number of applicants from 'Asia'
visa_df#df
visa_df['continent']#one column
con=visa_df['continent']=='Asia'#one class
np.sum(con)#1+1+1+1+0+1.......... tells how many times it repeted

np.int64(16861)

In [19]:
visa_df[con]#to extract the only asia rows

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
5,EZYV06,Asia,Master's,Y,N,2339,2012,South,78252.1400,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [22]:
con1=visa_df['continent']=='Africa'
np.sum(con1)

np.int64(551)

In [23]:
visa_df[con1]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.39,Year,Y,Certified
18,EZYV19,Africa,Master's,Y,N,4743,2004,Midwest,150441.13,Year,Y,Certified
74,EZYV75,Africa,Master's,Y,N,3705,2001,South,47170.76,Year,Y,Certified
194,EZYV195,Africa,Master's,Y,N,2180,1992,Midwest,113637.40,Year,Y,Certified
242,EZYV243,Africa,Bachelor's,N,Y,2509,2003,West,51886.04,Year,Y,Denied
...,...,...,...,...,...,...,...,...,...,...,...,...
25385,EZYV25386,Africa,Doctorate,Y,N,2513,1975,West,76348.20,Year,Y,Certified
25408,EZYV25409,Africa,Master's,Y,Y,1671,1992,Midwest,55756.35,Year,Y,Certified
25443,EZYV25444,Africa,Bachelor's,N,N,72892,2007,Northeast,215.10,Hour,Y,Certified
25446,EZYV25447,Africa,Master's,N,Y,2024,1971,South,42353.45,Year,Y,Certified
25474,EZYV25475,Africa,Doctorate,N,N,2594,1979,Northeast,51104.78,Year,Y,Certified

In [24]:
con2=visa_df['continent']=='North America'
np.sum(con2)

np.int64(3292)

In [25]:
visa_df[con2]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
7,EZYV08,North America,Bachelor's,Y,N,3035,1924,West,418.2298,Hour,Y,Denied
21,EZYV22,North America,Master's,Y,N,1706,2013,Midwest,137694.9800,Year,N,Certified
23,EZYV24,North America,High School,N,N,1517,1884,Midwest,90108.3800,Year,N,Certified
25,EZYV26,North America,Master's,N,N,1100,1997,Midwest,99489.6500,Year,Y,Certified
43,EZYV44,North America,Master's,Y,N,2582,1989,South,54614.4200,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25451,EZYV25452,North America,High School,Y,N,97,2013,Northeast,111518.5900,Year,N,Denied
25465,EZYV25466,North America,High School,N,N,2577,1995,South,481.2238,Hour,Y,Certified
25467,EZYV25468,North America,Master's,N,Y,2504,1882,Northeast,105900.6600,Year,Y,Certified
25469,EZYV25470,North America,Master's,Y,N,2261,1997,Northeast,273772.4700,Year,N,Certified
25470,EZYV25471,North America,Master's,Y,N,2272,1970,Northeast,516.4101,Hour,Y,Certified

In [35]:
cont_class=visa_df['continent'].unique()
freq=[]
for i in cont_class:
    con=visa_df['continent']==i
    freq.append(np.sum(con))
pd.DataFrame(zip(cont_class,freq),columns=['class','Frequency'])

           class  Frequency
0           Asia      16861
1         Africa        551
2  North America       3292
3         Europe       3732
4  South America        852
5        Oceania        192

**Value_Counts**

In [36]:
visa_df['continent'].value_counts()

continent
Asia             16861
Europe            3732
North America     3292
South America      852
Africa             551
Oceania            192
Name: count, dtype: int64

In [37]:
type(visa_df['continent'].value_counts())

pandas.core.series.Series

In [40]:
keys=visa_df['continent'].value_counts().keys().tolist()
keys

['Asia', 'Europe', 'North America', 'South America', 'Africa', 'Oceania']

In [41]:
values=visa_df['continent'].value_counts().values.tolist()
values

[16861, 3732, 3292, 852, 551, 192]

In [42]:
pd.DataFrame(zip(keys,values),columns=['Class','Frequency'])

           Class  Frequency
0           Asia      16861
1         Europe       3732
2  North America       3292
3  South America        852
4         Africa        551
5        Oceania        192

In [44]:
list(visa_df.groupby(by='continent'))

[('Africa',
           case_id continent education_of_employee has_job_experience  \
  4         EZYV05    Africa              Master's                  Y
  18        EZYV19    Africa              Master's                  Y
  74        EZYV75    Africa              Master's                  Y
  194      EZYV195    Africa              Master's                  Y
  242      EZYV243    Africa            Bachelor's                  N
  ...          ...       ...                   ...                ...
  25385  EZYV25386    Africa             Doctorate                  Y
  25408  EZYV25409    Africa              Master's                  Y
  25443  EZYV25444    Africa            Bachelor's                  N
  25446  EZYV25447    Africa              Master's                  N
  25474  EZYV25475    Africa             Doctorate                  N

        requires_job_training  no_of_employees  yr_of_estab  \
  4                         N             1082         2005
  18                        N             4743         2004
  74                        N             3705         2001
  194                       N             2180         1992
  242                       Y             2509         2003
  ...                     ...              ...          ...
  25385                     N             2513         1975
  25408                     Y             1671         1992
  25443                     N            72892         2007
  25446                     Y             2024         1971
  25474                     N             2594         1979

        region_of_employment  prevailing_wage unit_of_wage full_time_position  \
  4                    South        149907.39         Year                  Y
  18                 Midwest        150441.13         Year                  Y
  74                   South         47170.76         Year                  Y
  194                Midwest        113637.40         Year                  Y
  242                   West         51886.04         Year                  Y
  ...                    ...              ...          ...                ...
  25385                 West         76348.20         Year                  Y
  25408              Midwest         55756.35         Year                  Y
  25443            Northeast           215.10         Hour                  Y
  25446                South         42353.45         Year                  Y
  25474            Northeast         51104.78         Year                  Y

        case_status
  4       Certified
  18      Certified
  74      Certified
  194     Certified
  242        Denied
  ...           ...
  25385   Certified
  25408   Certified
  25443   Certified
  25446   Certified
  25474   Certified

  [551 rows x 12 columns]),
 ('Asia',
           case_id continent education_of_employee has_job_experience  \
  0         EZYV01      Asia           High School                  N
  1         EZYV02      Asia              Master's                  Y
  2         EZYV03      Asia            Bachelor's                  N
  3         EZYV04      Asia            Bachelor's                  N
  5         EZYV06      Asia              Master's                  Y
  ...          ...       ...                   ...                ...
  25475  EZYV25476      Asia            Bachelor's                  Y
  25476  EZYV25477      Asia           High School                  Y
  25477  EZYV25478      Asia              Master's                  Y
  25478  EZYV25479      Asia              Master's                  Y
  25479  EZYV25480      Asia            Bachelor's                  Y

        requires_job_training  no_of_employees  yr_of_estab  \
  0                         N            14513         2007
  1                         N             2412         2002
  2                         Y            44444         2008
  3                         N               98         1897
  5                         N             2339         2012
  ...                     ...              ...          ...
  25475                     Y             2601         2008
  25476                     N             3274         2006
  25477                     N             1121         1910
  25478                     Y             1918         1887
  25479                     N             3195         1960

        region_of_employment  prevailing_wage unit_of_wage full_time_position  \
  0                     West         592.2029         Hour                  Y
  1                Northeast       83425.6500         Year                  Y
  2                     West      122996.8600         Year                  Y
  3                     West       83434.0300         Year                  Y
  5                    South       78252.1400         Year                  Y
  ...                    ...              ...          ...                ...
  25475                South       77092.5700         Year                  Y
  25476            Northeast      279174.7900         Year                  Y
  25477                South      146298.8500         Year                  N
  25478                 West       86154.7700         Year                  Y
  25479              Midwest       70876.9100         Year                  Y

        case_status
  0          Denied
  1       Certified
  2          Denied
  3          Denied
  5       Certified
  ...           ...
  25475   Certified
  25476   Certified
  25477   Certified
  25478   Certified
  25479   Certified

  [16861 rows x 12 columns]),
 ('Europe',
           case_id continent education_of_employee has_job_experience  \
  9         EZYV10    Europe             Doctorate                  Y
  16        EZYV17    Europe              Master's                  Y
  24        EZYV25    Europe             Doctorate                  Y
  36        EZYV37    Europe           High School                  Y
  37        EZYV38    Europe              Master's                  Y
  ...          ...       ...                   ...                ...
  25435  EZYV25436    Europe            Bachelor's                  N
  25448  EZYV25449    Europe             Doctorate                  Y
  25460  EZYV25461    Europe              Master's                  Y
  25462  EZYV25463    Europe            Bachelor's                  N
  25466  EZYV25467    Europe            Bachelor's                  Y

        requires_job_training  no_of_employees  yr_of_estab  \
  9                         N             2251         1995
  16                        N            76638         1991
  24                        N              241         1981
  36                        N             2520         1981
  37                        Y               44         1965
  ...                     ...              ...          ...
  25435                     N             1606         1998
  25448                     N             4119         1971
  25460                     Y              413         1997
  25462                     Y             1715         2004
  25466                     N             1938         2005

        region_of_employment  prevailing_wage unit_of_wage full_time_position  \
  9                    South         67514.76         Year                  Y
  16                 Midwest          3706.79         Year                  Y
  24                 Midwest         71286.04         Year                  Y
  36                    West          2490.12         Year                  Y
  37                   South        110817.26         Year                  Y
  ...                    ...              ...          ...                ...
  25435                South        126329.96         Year                  Y
  25448                 West         86894.10         Year                  Y
  25460                 West          8263.47         Year                  Y
  25462                 West        166032.62         Year                  Y
  25466                 West          6973.40         Year                  Y

        case_status
  9       Certified
  16      Certified
  24      Certified
  36         Denied
  37      Certified
  ...           ...
  25435   Certified
  25448   Certified
  25460   Certified
  25462      Denied
  25466      Denied

  [3732 rows x 12 columns]),
 ('North America',
           case_id      continent education_of_employee has_job_experience  \
  7         EZYV08  North America            Bachelor's                  Y
  21        EZYV22  North America              Master's                  Y
  23        EZYV24  North America           High School                  N
  25        EZYV26  North America              Master's                  N
  43        EZYV44  North America              Master's                  Y
  ...          ...            ...                   ...                ...
  25451  EZYV25452  North America           High School                  Y
  25465  EZYV25466  North America           High School                  N
  25467  EZYV25468  North America              Master's                  N
  25469  EZYV25470  North America              Master's                  Y
  25470  EZYV25471  North America              Master's                  Y

        requires_job_training  no_of_employees  yr_of_estab  \
  7                         N             3035         1924
  21                        N             1706         2013
  23                        N             1517         1884
  25                        N             1100         1997
  43                        N             2582         1989
  ...                     ...              ...          ...
  25451                     N               97         2013
  25465                     N             2577         1995
  25467                     Y             2504         1882
  25469                     N             2261         1997
  25470                     N             2272         1970

        region_of_employment  prevailing_wage unit_of_wage full_time_position  \
  7                     West         418.2298         Hour                  Y
  21                 Midwest      137694.9800         Year                  N
  23                 Midwest       90108.3800         Year                  N
  25                 Midwest       99489.6500         Year                  Y
  43                   South       54614.4200         Year                  Y
  ...                    ...              ...          ...                ...
  25451            Northeast      111518.5900         Year                  N
  25465                South         481.2238         Hour                  Y
  25467            Northeast      105900.6600         Year                  Y
  25469            Northeast      273772.4700         Year                  N
  25470            Northeast         516.4101         Hour                  Y

        case_status
  7          Denied
  21      Certified
  23      Certified
  25      Certified
  43      Certified
  ...           ...
  25451      Denied
  25465   Certified
  25467   Certified
  25469   Certified
  25470   Certified

  [3292 rows x 12 columns]),
 ('Oceania',
           case_id continent education_of_employee has_job_experience  \
  241      EZYV242   Oceania             Doctorate                  Y
  288      EZYV289   Oceania            Bachelor's                  N
  708      EZYV709   Oceania            Bachelor's                  N
  955      EZYV956   Oceania              Master's                  N
  960      EZYV961   Oceania            Bachelor's                  N
  ...          ...       ...                   ...                ...
  24865  EZYV24866   Oceania             Doctorate                  N
  25150  EZYV25151   Oceania              Master's                  Y
  25196  EZYV25197   Oceania            Bachelor's                  Y
  25404  EZYV25405   Oceania             Doctorate                  Y
  25405  EZYV25406   Oceania              Master's                  Y

        requires_job_training  no_of_employees  yr_of_estab  \
  241                       N             2871         2009
  288                       N             2288         2011
  708                       N             3227         1928
  955                       N            17541         1986
  960                       N              363         2013
  ...                     ...              ...          ...
  24865                     Y             3487         1930
  25150                     N             1076         1869
  25196                     N              385         2000
  25404                     N              429         2006
  25405                     N             1829         1993

        region_of_employment  prevailing_wage unit_of_wage full_time_position  \
  241                  South         56606.54        Month                  Y
  288                   West         82385.60         Year                  Y
  708                Midwest         92422.74         Year                  Y
  955              Northeast         75224.53         Year                  Y
  960              Northeast         97469.69         Year                  Y
  ...                    ...              ...          ...                ...
  24865                 West         59969.55         Year                  Y
  25150            Northeast         87467.12         Year                  N
  25196                South         94420.47         Year                  Y
  25404                 West         27819.35         Year                  Y
  25405            Northeast         74975.25         Year                  Y

        case_status
  241     Certified
  288        Denied
  708     Certified
  955        Denied
  960        Denied
  ...           ...
  24865      Denied
  25150   Certified
  25196   Certified
  25404   Certified
  25405   Certified

  [192 rows x 12 columns]),
 ('South America',
           case_id      continent education_of_employee has_job_experience  \
  121      EZYV122  South America            Bachelor's                  N
  130      EZYV131  South America           High School                  N
  171      EZYV172  South America            Bachelor's                  Y
  188      EZYV189  South America              Master's                  Y
  224      EZYV225  South America            Bachelor's                  N
  ...          ...            ...                   ...                ...
  25319  EZYV25320  South America              Master's                  Y
  25364  EZYV25365  South America            Bachelor's                  Y
  25413  EZYV25414  South America              Master's                  Y
  25444  EZYV25445  South America              Master's                  Y
  25455  EZYV25456  South America            Bachelor's                  N

        requires_job_training  no_of_employees  yr_of_estab  \
  121                       N             1415         1913
  130                       N             2554         2005
  171                       N             5461         1979
  188                       N             1551         1989
  224                       N             1004         1960
  ...                     ...              ...          ...
  25319                     N             1186         2004
  25364                     N             1269         2000
  25413                     N             2423         2005
  25444                     N             1081         1838
  25455                     N            24335         1993

        region_of_employment  prevailing_wage unit_of_wage full_time_position  \
  121              Northeast        53114.020         Year                  Y
  130                Midwest       247393.010         Year                  Y
  171              Northeast         9078.620         Year                  Y
  188                   West          630.660         Year                  Y
  224                Midwest       135792.520         Year                  Y
  ...                    ...              ...          ...                ...
  25319                 West        75773.380         Year                  Y
  25364                South         5769.540         Year                  Y
  25413              Midwest       163067.990         Year                  Y
  25444            Northeast          156.607         Hour                  Y
  25455              Midwest        97393.490         Year                  Y

        case_status
  121        Denied
  130     Certified
  171     Certified
  188     Certified
  224     Certified
  ...           ...
  25319      Denied
  25364   Certified
  25413   Certified
  25444   Certified
  25455   Certified

  [852 rows x 12 columns])]

In [47]:
visa_df.groupby(by='continent').count()

,case_id,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
continent,,,,,,,,,,,
Africa,551,551,551,551,551,551,551,551,551,551,551
Asia,16861,16861,16861,16861,16861,16861,16861,16861,16861,16861,16861
Europe,3732,3732,3732,3732,3732,3732,3732,3732,3732,3732,3732
North America,3292,3292,3292,3292,3292,3292,3292,3292,3292,3292,3292
Oceania,192,192,192,192,192,192,192,192,192,192,192
South America,852,852,852,852,852,852,852,852,852,852,852

In [48]:
visa_df.groupby(by='continent').count()['case_id']

continent
Africa             551
Asia             16861
Europe            3732
North America     3292
Oceania            192
South America      852
Name: case_id, dtype: int64