In [1]:
import numpy as np
import pandas as pd

**How to create a null values in a data**
- None
- np.nan

In [3]:
d={'Names':['Ramesh','Suresh',None,'Mahesh'],
   'Age':[None,22,24,25],
   'City':['Hyd','Blr','Pune',None]}
df1=pd.DataFrame(d)
df1

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2    None  24.0  Pune
3  Mahesh  25.0  None

In [4]:
df1.to_csv('data.csv',index=False)

In [5]:
d={'Names':['Ramesh','Suresh',np.nan,'Mahesh'],
   'Age':[np.nan,22,24,25],
   'City':['Hyd','Blr','Pune',np.nan]}
df2=pd.DataFrame(d)
df2

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2     NaN  24.0  Pune
3  Mahesh  25.0   NaN

In [6]:
df2.to_csv('data1.csv',index=False)

- Categorical data use **None**
- Numerical data use **np.nan**

In [7]:
np.nan+10

nan

In [8]:
None+10

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [10]:
df1.isnull()
#is null is a method where eve the Null value is there it displays as true

   Names    Age   City
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False   True

In [11]:
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [16]:
df1
df1.values
#df1.dtypes
#df1.isnull()
#df1.isnull().sum()

array([['Ramesh', nan, 'Hyd'],
       ['Suresh', 22.0, 'Blr'],
       [None, 24.0, 'Pune'],
       ['Mahesh', 25.0, None]], dtype=object)

**Fill the values**m

In [18]:
#Random filling
df1.fillna(30)

    Names   Age  City
0  Ramesh  30.0   Hyd
1  Suresh  22.0   Blr
2      30  24.0  Pune
3  Mahesh  25.0    30

In [19]:
#select one column and fill with value
df1['City'].fillna('Delhi')

0      Hyd
1      Blr
2     Pune
3    Delhi
Name: City, dtype: object

In [20]:
#i am not doing inplace=True
df1.fillna(30)
df1['City'].fillna('Delhi')

0      Hyd
1      Blr
2     Pune
3    Delhi
Name: City, dtype: object

In [21]:
df1

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2    None  24.0  Pune
3  Mahesh  25.0  None

In [27]:
#pad,ffill,bfill,backfill
#axis=0, axis=1
df1.fillna(method='pad')

C:\Users\B VENKATA SAILAJA\AppData\Local\Temp\ipykernel_33776\1888257539.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad')

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2  Suresh  24.0  Pune
3  Mahesh  25.0  Pune

In [23]:
df1.fillna(method='pad',axis=1)

C:\Users\B VENKATA SAILAJA\AppData\Local\Temp\ipykernel_33776\1258234312.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad',axis=1)

    Names     Age  City
0  Ramesh  Ramesh   Hyd
1  Suresh    22.0   Blr
2    None    24.0  Pune
3  Mahesh    25.0  25.0

In [24]:
df1.fillna(method='bfill')

C:\Users\B VENKATA SAILAJA\AppData\Local\Temp\ipykernel_33776\2949398996.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill')

    Names   Age  City
0  Ramesh  22.0   Hyd
1  Suresh  22.0   Blr
2  Mahesh  24.0  Pune
3  Mahesh  25.0  None

In [25]:
df1.fillna(method='bfill',axis=1)

C:\Users\B VENKATA SAILAJA\AppData\Local\Temp\ipykernel_33776\2900121331.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill',axis=1)

    Names   Age  City
0  Ramesh   Hyd   Hyd
1  Suresh  22.0   Blr
2    24.0  24.0  Pune
3  Mahesh  25.0  None

In [28]:
df1.fillna(method='ffill')

C:\Users\B VENKATA SAILAJA\AppData\Local\Temp\ipykernel_33776\598575452.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='ffill')

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2  Suresh  24.0  Pune
3  Mahesh  25.0  Pune

In [29]:
df1.fillna(method='ffill',axis=1)

C:\Users\B VENKATA SAILAJA\AppData\Local\Temp\ipykernel_33776\209249745.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='ffill',axis=1)

    Names     Age  City
0  Ramesh  Ramesh   Hyd
1  Suresh    22.0   Blr
2    None    24.0  Pune
3  Mahesh    25.0  25.0

- mean
- median
- mode

In [32]:
df1

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2    None  24.0  Pune
3  Mahesh  25.0  None

In [31]:
age_mean=df1['Age'].mean()
df1['Age'].fillna(age_mean)

0    23.666667
1    22.000000
2    24.000000
3    25.000000
Name: Age, dtype: float64

**Situation-1**

In [33]:
#There is No particular Rule how to fill the missing values
#it is completely based on situation

In [37]:
Gender=['Male','Female',None]
d1=pd.DataFrame(Gender,columns=['Gender'])
d1#i want to handover this data to my sstudents with not encode

   Gender
0    Male
1  Female
2    None

In [38]:
d={'Female':0,'Male':1}t
d1['Gender']=d1['Gender'].map(d)
d1

   Gender
0     1.0
1     0.0
2     NaN

In [40]:
#the student think i want to fill a missing 
#data is numerical: mean
(1+0)/2

0.5

In [42]:
Gender=['Male','Female',None]
d1=pd.DataFrame(Gender,columns=['Gender'])
d1

   Gender
0    Male
1  Female
2    None

**Situation-2**

In [43]:
#ML algo
#Churn : stay or not stay
churn=['stay','not_stay',None]
churn=[0,1,None]
churn=[0,1,0.5]

**Situation-3**

In [45]:
#No of days
[20,25,np.nan,31]
(20+25+31)/3

25.333333333333332

**Situation-4**

In [47]:
course=['DS','Ai','DS','Deveops','AI','Deveops','AI']
fee=[30000,2700,30000,22000,3000,22000,np.nan]
pd.DataFrame(zip(course,fee))
#first group by with course
#then take corresponding course values only

         0        1
0       DS  30000.0
1       Ai   2700.0
2       DS  30000.0
3  Deveops  22000.0
4       AI   3000.0
5  Deveops  22000.0
6       AI      NaN

**KNNImputer**

- KNN: K-Nearest neighbours
- where K is Number
- instead of taking avg of all the values data
     - first we will find the neighbours who are close with missing data
     - by using Euclidian distance calculation will identify the neighbour rows first
     - suppose k=2 will identify the 2 closest point first
     - those closest rows values will take it, will calculate the mean
     - Finally will fill with the mean

In [48]:
salary=[50000,np.nan,70000,90000]
age=[25,28,30,40]
df=pd.DataFrame(zip(salary,age),
                columns=['Salary','Age'])
df

    Salary  Age
0  50000.0   25
1      NaN   28
2  70000.0   30
3  90000.0   40

- Sklearn
   - impute
     - KNNImpute

In [52]:
from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=2)
pd.DataFrame(imputer.fit_transform(df))

         0     1
0  50000.0  25.0
1  60000.0  28.0
2  70000.0  30.0
3  90000.0  40.0