In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**Data Science life cycle**

Data read
    |
Data Cleaning
    |
Data Analysis(from session 1 to 5)
    |
feature engineering(changing)
    |
feature Selection
    |
model development
    |
model evaluation
    |
model tuning
    |
model deployment`

**Feature Engineering**
- cateogorical to numerical
- transform
- encoading
- scaling and normalization
- missing values  and value analysis

**Feature Engineering**
- so far we have performedfeature analysis
  - Data Freame quick checks
  - cateogorical column analysis
  - bar charts, pie charts
  - numerical columns
  - histogram, box plot, outliers
  - bi-multi variente aanalysis
  - corrlation etc
- Now we need to learn Feature Engeneering
   - we will create a new columns for better ML model
   - we will perfrom **Encoading** which is converting categorical to numerica
   - we will do data **transformation**
   - we will perform **Scaling: Standardization and Normalization**
   - we will perform the **missing values analysis**
- Simply feature engineering means our data will be modified

In [4]:
visa_df=pd.read_csv(r"C:\Users\B VENKATA SAILAJA\Documents\Datasets_GenAi\visadataset.csv")
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [13]:
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns
cat,num

(Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
        'requires_job_training', 'region_of_employment', 'unit_of_wage',
        'full_time_position', 'case_status'],
       dtype='object'),
 Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object'))

**Case_Status**

In [32]:
#first check how many uqniue labels are there in case_status
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [33]:
#create a dictionary
d={'Certified':0,'Denied':1}

In [34]:
#map the above dictionary with original column
visa_df['case_status']=visa_df['case_status'].map(d)
visa_df['case_status']

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [16]:
visa_df['education_of_employee'].unique()

array(['High School', "Master's", "Bachelor's", 'Doctorate'], dtype=object)

In [19]:
#create a dictionary
e={'High School':0,"Master's":1,"Bachelor's":2,'Doctorate':3}

In [20]:
#map the above dictionary with original column
visa_df['education_of_employee']=visa_df['education_of_employee'].map(e)
visa_df['education_of_employee']

0        0
1        1
2        2
3        2
4        1
        ..
25475    2
25476    0
25477    1
25478    1
25479    2
Name: education_of_employee, Length: 25480, dtype: int64

In [35]:
labels=sorted(visa_df['education_of_employee'].unique())
f={j:i for i,j in enumerate(labels)}
visa_df['education_of_employee'].map(f)

0        2
1        3
2        0
3        0
4        3
        ..
25475    0
25476    2
25477    3
25478    3
25479    0
Name: education_of_employee, Length: 25480, dtype: int64

In [36]:
f

{"Bachelor's": 0, 'Doctorate': 1, 'High School': 2, "Master's": 3}

In [37]:
education     label encoder      ordinal endcoder
====================================================
highschool         1                0
bachelors          0                1
masters            2                2 
ph.d               3                3

1 0 2 3==>MLmodel sees this: 3>2>1>0
which indicates: Ph.D>Masters>highschool>Bachelors

SyntaxError: invalid syntax (289066589.py, line 1)

In [38]:
visa_df=pd.read_csv(r"C:\Users\B VENKATA SAILAJA\Documents\Datasets_GenAi\visadataset.csv")
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

- sklearn:**package**
    - preprocessing:**module**
      - label Encoder:**class**
          - fit_transfrom:**method**

import sklearn
sklearn.preprocessing

@ it can written in the form of 
from sklearn import preprocessing
dir(preprocessing)=>

In [ ]:
         -fit_transform: **method** 
import sklearn 
sklearn.preprocessing 
from sklearn 
import preprocessing 
dir(preprocessing)== LabelEncoder 
preprocessing.LabelEncoder 
from sklearn.preprocessing import LabelEncoder 
le=LabelEncoder()  # class le.fit_transform() # read the class # save the class # apply fit_transform

In [ ]:
from sklearn.preprocessing import LabelEncoder 
le=LabelEncoder() 
le.fit_transform 

from sklearn.preprocessing import  OrdinalEncoder 
oe=OrdinalEncoder 
oe.fit_transform

In [ ]:
**fit transform**
- fit : created a dictionary (find something)
- transform : using above finding we are modify the data 

from sklearn.module import class va=class() 
va=fit 
va=fit_transform 
# only fit is for finding something # fit_transform is for modifying

In [5]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

**Label Encoder**

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
visa_df['case_status']=le.fit_transform(visa_df['case_status'])
visa_df['case_status']

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [12]:
visa_df=pd.read_csv(r"C:\Users\B VENKATA SAILAJA\Documents\Datasets_GenAi\visadataset.csv")
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [15]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat[1:]: 
    visa_df[i]=le.fit_transform(visa_df[i])

In [16]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

In [17]:
visa_df=pd.read_csv(r"C:\Users\B VENKATA SAILAJA\Documents\Datasets_GenAi\visadataset.csv")

In [19]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
for i in cat[1:]:
    visa_df[i]=oe.fit_transform(visa_df[[i]])

In [20]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1.0,2.0,0.0,0.0,14513,2007,4.0,592.2029,0.0,1.0,1.0
1,EZYV02,1.0,3.0,1.0,0.0,2412,2002,2.0,83425.6500,3.0,1.0,0.0
2,EZYV03,1.0,0.0,0.0,1.0,44444,2008,4.0,122996.8600,3.0,1.0,1.0
3,EZYV04,1.0,0.0,0.0,0.0,98,1897,4.0,83434.0300,3.0,1.0,1.0
4,EZYV05,0.0,3.0,1.0,0.0,1082,2005,3.0,149907.3900,3.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1.0,0.0,1.0,1.0,2601,2008,3.0,77092.5700,3.0,1.0,0.0
25476,EZYV25477,1.0,2.0,1.0,0.0,3274,2006,2.0,279174.7900,3.0,1.0,0.0
25477,EZYV25478,1.0,3.0,1.0,0.0,1121,1910,3.0,146298.8500,3.0,0.0,0.0
25478,EZYV25479,1.0,3.0,1.0,1.0,1918,1887,4.0,86154.7700,3.0,1.0,0.0
25479,EZYV25480,1.0,0.0,1.0,0.0,3195,1960,1.0,70876.9100,3.0,1.0,0.0

In [21]:
visa_df=pd.read_csv(r"C:\Users\B VENKATA SAILAJA\Documents\Datasets_GenAi\visadataset.csv")

**pd.get_dummies**

- get dummies id a way to represent the categorical columns to numerical only
- first it wil check what are the labels in a column
- for example case status has two labels
     - Denied and Certified
- so it will create two new columns based on albels
     - col1: case_status_Denied
     - col2: case_status_certified
- both columns are indepent to each other that means 90 degrees.

case_status   |  case_status_Denied  | case_status_Certified 
 Denied       |         1            |           0           
 Certified    |         0            |           1           
 Certified    |         0            |           1           

- **It is also called as one hot encoder**
- it makes new columns are independent to each othe
- some of ML algorithm expect that columns should be **independent** each other and those 2 columns don't have relation.

In [23]:
pd.get_dummies(visa_df['case_status'])

       Certified  Denied
0          False    True
1           True   False
2          False    True
3          False    True
4           True   False
...          ...     ...
25475       True   False
25476       True   False
25477       True   False
25478       True   False
25479       True   False

[25480 rows x 2 columns]

In [24]:
pd.get_dummies(visa_df['case_status'],
              dtype=int)

       Certified  Denied
0              0       1
1              1       0
2              0       1
3              0       1
4              1       0
...          ...     ...
25475          1       0
25476          1       0
25477          1       0
25478          1       0
25479          1       0

[25480 rows x 2 columns]