In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Step-2: Read the csv**

In [2]:
visa_csv=pd.read_csv(r"C:\Users\B VENKATA SAILAJA\Documents\Datasets_GenAi\Visadataset.csv")
visa_csv

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [3]:
bank=pd.read_csv(r"C:\Users\B VENKATA SAILAJA\Documents\Datasets_GenAi\bank.csv")
bank

     age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0     30;"unemployed";"married";"primary";"no";1787;...
1     33;"services";"married";"secondary";"no";4789;...
2     35;"management";"single";"tertiary";"no";1350;...
3     30;"management";"married";"tertiary";"no";1476...
4     59;"blue-collar";"married";"secondary";"no";0;...
...                                                 ...
4516  33;"services";"married";"secondary";"no";-333;...
4517  57;"self-employed";"married";"tertiary";"yes";...
4518  57;"technician";"married";"secondary";"no";295...
4519  28;"blue-collar";"married";"secondary";"no";11...
4520  44;"entrepreneur";"single";"tertiary";"no";113...

[4521 rows x 1 columns]

In [13]:
bank=pd.read_csv(r"C:\Users\B VENKATA SAILAJA\Documents\Datasets_GenAi\bank.csv",sep=';')
bank

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

**Step-3:Data Qucik Checks**

# us visa-df
- visa_df.shape
- visa_df.size
- head
- tail
- dtypes
- columns
- isnull
- info

In [3]:
visa_csv.shape
print(f"the number of columns are: {visa_csv}")

the number of columns are:          case_id continent education_of_employee has_job_experience  \
0         EZYV01      Asia           High School                  N
1         EZYV02      Asia              Master's                  Y
2         EZYV03      Asia            Bachelor's                  N
3         EZYV04      Asia            Bachelor's                  N
4         EZYV05    Africa              Master's                  Y
...          ...       ...                   ...                ...
25475  EZYV25476      Asia            Bachelor's                  Y
25476  EZYV25477      Asia           High School                  Y
25477  EZYV25478      Asia              Master's                  Y
25478  EZYV25479      Asia              Master's                  Y
25479  EZYV25480      Asia            Bachelor's                  Y

      requires_job_training  no_of_employees  yr_of_estab  \
0                         N            14513         2007
1                         N             2412         2002
2                         Y            44444         2008
3                         N               98         1897
4                         N             1082         2005
...                     ...              ...          ...
25475                     Y             2601         2008
25476                     N             3274         2006
25477                     N             1121         1910
25478                     Y             1918         1887
25479                     N             3195         1960

      region_of_employment  prevailing_wage unit_of_wage full_time_position  \
0                     West         592.2029         Hour                  Y
1                Northeast       83425.6500         Year                  Y
2                     West      122996.8600         Year                  Y
3                     West       83434.0300         Year                  Y
4                    South      149907.3900         Year                  Y
...                    ...              ...          ...                ...
25475                South       77092.5700         Year                  Y
25476            Northeast      279174.7900         Year                  Y
25477                South      146298.8500         Year                  N
25478                 West       86154.7700         Year                  Y
25479              Midwest       70876.9100         Year                  Y

      case_status
0          Denied
1       Certified
2          Denied
3          Denied
4       Certified
...           ...
25475   Certified
25476   Certified
25477   Certified
25478   Certified
25479   Certified

[25480 rows x 12 columns]

In [4]:
visa_csv.shape

(25480, 12)

In [5]:
visa_csv.size#row X column
#number of entries

305760

In [8]:
cols=visa_csv.columns
cols
#what are the colums

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [9]:
cols.index('continent')

AttributeError: 'Index' object has no attribute 'index'

In [6]:
visa_csv.columns.tolist()

['case_id',
 'continent',
 'education_of_employee',
 'has_job_experience',
 'requires_job_training',
 'no_of_employees',
 'yr_of_estab',
 'region_of_employment',
 'prevailing_wage',
 'unit_of_wage',
 'full_time_position',
 'case_status']

In [9]:
visa_csv['continent']

0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
          ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia
Name: continent, Length: 25480, dtype: object

In [12]:
visa_csv['continent'].values#it is series(single brace)

array(['Asia', 'Asia', 'Asia', ..., 'Asia', 'Asia', 'Asia'],
      shape=(25480,), dtype=object)

In [13]:
visa_csv[['continent','case_status']]#now it is dataframe(Double braces)

      continent case_status
0          Asia      Denied
1          Asia   Certified
2          Asia      Denied
3          Asia      Denied
4        Africa   Certified
...         ...         ...
25475      Asia   Certified
25476      Asia   Certified
25477      Asia   Certified
25478      Asia   Certified
25479      Asia   Certified

[25480 rows x 2 columns]

In [14]:
visa_csv[['continent','case_status']].values

array([['Asia', 'Denied'],
       ['Asia', 'Certified'],
       ['Asia', 'Denied'],
       ...,
       ['Asia', 'Certified'],
       ['Asia', 'Certified'],
       ['Asia', 'Certified']], shape=(25480, 2), dtype=object)

In [15]:
#1D is only one list:raw data of specific column
visa_csv['continent'].values

array(['Asia', 'Asia', 'Asia', ..., 'Asia', 'Asia', 'Asia'],
      shape=(25480,), dtype=object)

In [16]:
#2d is a list has 2 values 2 columns

In [ ]:
visa_df['continent'] # s
visa_df[['continent']] # df
visa_df.iloc[[100,200,300],3] #s
visa_df.iloc[[100,200,300],[3]] # df
visa_df.loc[[100,200,300],'continent'] # s
visa_df.loc[[100,200,300],['continent']] # df

**Task-1**(converting into data frame)

**Dtypes**

- every sreies is a key value pair
- every series is dictionary
- in dictionary if we want keys: .key()
- in dictionary if we want values: .values

In [17]:
visa_csv.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [18]:
visa_csv.dtypes.keys()

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [19]:
visa_csv.dtypes.values

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

In [20]:
visa_csv.dtypes.tolist()

[dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('int64'),
 dtype('int64'),
 dtype('O'),
 dtype('float64'),
 dtype('O'),
 dtype('O'),
 dtype('O')]

In [24]:
keys=visa_csv.dtypes.keys().tolist()
values=visa_csv.dtypes.values.tolist()
print(f'Keys={keys}')
print(f'Values={values}')

Keys=['case_id', 'continent', 'education_of_employee', 'has_job_experience', 'requires_job_training', 'no_of_employees', 'yr_of_estab', 'region_of_employment', 'prevailing_wage', 'unit_of_wage', 'full_time_position', 'case_status']
Values=[dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'), dtype('O'), dtype('O'), dtype('O')]

In [27]:
pd.DataFrame(zip(keys,values),columns=['Name','Data type'])

                     Name Data type
0                 case_id    object
1               continent    object
2   education_of_employee    object
3      has_job_experience    object
4   requires_job_training    object
5         no_of_employees     int64
6             yr_of_estab     int64
7    region_of_employment    object
8         prevailing_wage   float64
9            unit_of_wage    object
10     full_time_position    object
11            case_status    object

In [ ]:
#every student must known 1-how to convert a series to dataframe(dic->keys tolist->values)
#                         2-how to create a df when you have a list

In [29]:
pd.DataFrame(visa_csv.dtypes)

                             0
case_id                 object
continent               object
education_of_employee   object
has_job_experience      object
requires_job_training   object
no_of_employees          int64
yr_of_estab              int64
region_of_employment    object
prevailing_wage        float64
unit_of_wage            object
full_time_position      object
case_status             object

In [30]:
df=pd.DataFrame(visa_csv.dtypes).reset_index()
df.columns=['Name','Data type']
df

                     Name Data type
0                 case_id    object
1               continent    object
2   education_of_employee    object
3      has_job_experience    object
4   requires_job_training    object
5         no_of_employees     int64
6             yr_of_estab     int64
7    region_of_employment    object
8         prevailing_wage   float64
9            unit_of_wage    object
10     full_time_position    object
11            case_status    object

**Task-2**

In [32]:
visa_csv.dtypes
#idea
#extract keys and values
#apply the for loop on values
#for i,j in zip(values,keys)
#if i =='object':
#       j

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [11]:
keys=visa_csv.dtypes.keys().tolist()
values=visa_csv.dtypes.values.tolist()
cat,num=[],[]
for i,j in zip(values,keys):
    if j=='object':
        cat.append(i)
    else:
        num.append(j)
cat,num

([],
 ['case_id',
  'continent',
  'education_of_employee',
  'has_job_experience',
  'requires_job_training',
  'no_of_employees',
  'yr_of_estab',
  'region_of_employment',
  'prevailing_wage',
  'unit_of_wage',
  'full_time_position',
  'case_status'])

**Salect_dtypes**

In [40]:
visa_csv.select_dtypes(include='object')

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,region_of_employment,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,West,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,Northeast,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,West,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,West,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,South,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,South,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,Northeast,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,South,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,West,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,Midwest,Year,Y,Certified

In [41]:
visa_csv.select_dtypes(include='object').columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [12]:
visa_csv.select_dtypes(exclude='object')

       no_of_employees  yr_of_estab  prevailing_wage
0                14513         2007         592.2029
1                 2412         2002       83425.6500
2                44444         2008      122996.8600
3                   98         1897       83434.0300
4                 1082         2005      149907.3900
...                ...          ...              ...
25475             2601         2008       77092.5700
25476             3274         2006      279174.7900
25477             1121         1910      146298.8500
25478             1918         1887       86154.7700
25479             3195         1960       70876.9100

[25480 rows x 3 columns]

In [43]:
visa_csv.select_dtypes(exclude='object').columns

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')